### ISSUE TITLE
[BUG] Object of type 'generator' has no len()

### ISSUE THREAD

**Issue by feserm** [nfdi4plants/ARCtrl#342]
**Describe the bug**
ARCtrl in python is not able to read ARCs.

**To Reproduce**
Using the code provided in /docs branch update-docs-v2, execute read() on ArcPrototype

**Screenshots**
Traceback (most recent call last):
  File "/home/ubuntu/test-dataset/main.py", line 57, in <module>
    arc = read('/home/ubuntu/test-dataset/ArcPrototype-main/')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/test-dataset/main.py", line 53, in read
    arc.SetISAFromContracts(fcontracts)
  File "/home/ubuntu/test-dataset/mira3.12/lib/python3.12/site-packages/arctrl/arc.py", line 197, in SetISAFromContracts
    investigation: ArcInvestigation = ARCAux_getArcInvestigationFromContracts(contracts)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/test-dataset/mira3.12/lib/python3.12/site-packages/arctrl/arc.py", line 58, in ARCAux_getArcInvestigationFromContracts
    return exactly_one(choose(chooser, contracts, None))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/test-dataset/mira3.12/lib/python3.12/site-packages/arctrl/fable_modules/fable_library/array_.py", line 647, in choose
    for i in range(0, (len(array) - 1) + 1, 1):
                       ^^^^^^^^^^
TypeError: object of type 'generator' has no len()

**OS and framework information (please complete the following information):**
 - OS: Ubuntu
 - OS Version 22.04
 - Python: 3.12.2 or 3.11.9

**Comment by Freymaurer** [comment]
This issue has been fixed! Docs are updated and can be found on branch `update_docs_v2`
